// Copyright 2015 The etcd Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package raft

import (
	"errors"

	pb "github.com/pingcap-incubator/tinykv/proto/pkg/eraftpb"
)

// ErrStepLocalMsg is returned when try to step a local raft message
// Local messages such as MsgHup and MsgBeat are generated by the local node
// itself, so they should not be injected through the network-facing Step API.
var ErrStepLocalMsg = errors.New("raft: cannot step raft local message")

// ErrStepPeerNotFound is returned when try to step a response message
// but there is no peer found in raft.Prs for that node.
// This protects the raft state machine from applying responses sent by stale
// or unknown peers.
var ErrStepPeerNotFound = errors.New("raft: cannot step as peer not found")

// SoftState provides state that is volatile and does not need to be persisted to the WAL.
// It is mainly used by the upper layer to observe leader and role changes.
type SoftState struct {
	Lead      uint64
	RaftState StateType
}

// Ready encapsulates the entries and messages that are ready to read,
// be saved to stable storage, committed or sent to other peers.
// All fields in Ready are read-only.
// The normal lifecycle is: persist HardState, Entries, and Snapshot first;
// send Messages after persistence; apply CommittedEntries to the state
// machine; then call Advance to move RawNode's internal progress forward.
type Ready struct {
	// The current volatile state of a Node.
	// SoftState will be nil if there is no update.
	// It is not required to consume or store SoftState.
	*SoftState

	// The current state of a Node to be saved to stable storage BEFORE
	// Messages are sent.
	// HardState will be equal to empty state if there is no update.
	pb.HardState

	// Entries specifies entries to be saved to stable storage BEFORE
	// Messages are sent.
	Entries []pb.Entry

	// Snapshot specifies the snapshot to be saved to stable storage.
	Snapshot pb.Snapshot

	// CommittedEntries specifies entries to be committed to a
	// store/state-machine. These have previously been committed to stable
	// store.
	CommittedEntries []pb.Entry

	// Messages specifies outbound messages to be sent AFTER Entries are
	// committed to stable storage.
	// If it contains a MessageType_MsgSnapshot message, the application MUST report back to raft
	// when the snapshot has been received or has failed by calling ReportSnapshot.
	Messages []pb.Message
}

// RawNode is a wrapper of Raft.
// It is the boundary between the pure raft state machine and the upper storage
// or network layer. The upper layer drives raft through RawNode methods and
// consumes raft outputs through the Ready/Advance lifecycle.
type RawNode struct {
	Raft *Raft
	// Your Data Here (2A).
}

// NewRawNode returns a new RawNode given configuration and a list of raft peers.
// It should build the underlying Raft object and remember the previous
// SoftState/HardState so HasReady can later tell whether anything changed.
func NewRawNode(config *Config) (*RawNode, error) {
	// Your Code Here (2A).
	return nil, nil
}

// Tick advances the internal logical clock by a single tick.
// The upper layer calls this periodically; raft uses it to detect election
// timeout and to trigger leader heartbeats.
func (rn *RawNode) Tick() {
	rn.Raft.tick()
}

// Campaign causes this RawNode to transition to candidate state.
// It does this by injecting MsgHup, which is raft's local "start election"
// signal.
func (rn *RawNode) Campaign() error {
	return rn.Raft.Step(pb.Message{
		MsgType: pb.MessageType_MsgHup,
	})
}

// Propose proposes data be appended to the raft log.
// The data is wrapped as a normal log entry and passed into raft as
// MsgPropose. Only the leader can append and replicate it successfully.
func (rn *RawNode) Propose(data []byte) error {
	ent := pb.Entry{Data: data}
	return rn.Raft.Step(pb.Message{
		MsgType: pb.MessageType_MsgPropose,
		From:    rn.Raft.id,
		Entries: []*pb.Entry{&ent}})
}

// ProposeConfChange proposes a config change.
// This only proposes a special configuration-change log entry. The membership
// is not changed here; it changes after the entry is committed and the upper
// layer calls ApplyConfChange.
func (rn *RawNode) ProposeConfChange(cc pb.ConfChange) error {
	data, err := cc.Marshal()
	if err != nil {
		return err
	}
	ent := pb.Entry{EntryType: pb.EntryType_EntryConfChange, Data: data}
	return rn.Raft.Step(pb.Message{
		MsgType: pb.MessageType_MsgPropose,
		Entries: []*pb.Entry{&ent},
	})
}

// ApplyConfChange applies a config change to the local node.
// It runs after a conf-change entry is committed, and returns the new ConfState
// that should be persisted in snapshots. A None node means "no actual change".
func (rn *RawNode) ApplyConfChange(cc pb.ConfChange) *pb.ConfState {
	if cc.NodeId == None {
		return &pb.ConfState{Nodes: nodes(rn.Raft)}
	}
	switch cc.ChangeType {
	case pb.ConfChangeType_AddNode:
		rn.Raft.addNode(cc.NodeId)
	case pb.ConfChangeType_RemoveNode:
		rn.Raft.removeNode(cc.NodeId)
	default:
		panic("unexpected conf type")
	}
	return &pb.ConfState{Nodes: nodes(rn.Raft)}
}

// Step advances the state machine using the given message.
// Network messages enter raft here. Local-only messages are rejected, and
// response messages must come from a known peer.
func (rn *RawNode) Step(m pb.Message) error {
	// ignore unexpected local messages receiving over network
	if IsLocalMsg(m.MsgType) {
		return ErrStepLocalMsg
	}
	if pr := rn.Raft.Prs[m.From]; pr != nil || !IsResponseMsg(m.MsgType) {
		return rn.Raft.Step(m)
	}
	return ErrStepPeerNotFound
}

// Ready returns the current point-in-time state of this RawNode.
// It gathers everything the upper layer must handle now: new unstable entries,
// committed entries, outbound messages, snapshots, and changed soft/hard state.
func (rn *RawNode) Ready() Ready {
	// Your Code Here (2A).
	return Ready{}
}

// HasReady called when RawNode user need to check if any Ready pending.
// It is a cheap pre-check for Ready. It should become true when there is a
// state change, unstable log or snapshot, committed-but-unapplied entry, or
// outbound message waiting.
func (rn *RawNode) HasReady() bool {
	// Your Code Here (2A).
	return false
}

// Advance notifies the RawNode that the application has applied and saved progress in the
// last Ready results.
// It pairs with Ready: after the upper layer persists entries and applies
// committed entries, Advance updates stabled/applied progress and prepares the
// next Ready batch.
func (rn *RawNode) Advance(rd Ready) {
	// Your Code Here (2A).
}

// GetProgress return the Progress of this node and its peers, if this
// node is leader.
// It is used for inspection/debugging of replication progress. Followers return
// an empty map because only the leader owns authoritative Progress data.
func (rn *RawNode) GetProgress() map[uint64]Progress {
	prs := make(map[uint64]Progress)
	if rn.Raft.State == StateLeader {
		for id, p := range rn.Raft.Prs {
			prs[id] = *p
		}
	}
	return prs
}

// TransferLeader tries to transfer leadership to the given transferee.
// This requests, but does not guarantee, a leadership transfer. Whether it
// succeeds depends on raft state, especially whether the target has caught up.
func (rn *RawNode) TransferLeader(transferee uint64) {
	_ = rn.Raft.Step(pb.Message{MsgType: pb.MessageType_MsgTransferLeader, From: transferee})
}
